spring.application.name=flashcardapp
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.pattern=IP: %h | Time: %t | Request: "%r" | Status: %s | Response Time: %D ms | Device: %{User-Agent}i
server.tomcat.basedir=.